# Generated by Django 5.0.3 on 2024-04-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Linkfeed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alloweddomain",
            name="domain",
            field=models.URLField(blank=True, null=True),
        ),
    ]
