# Generated by Django 5.0.3 on 2024-04-22 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Linkfeed", "0002_alter_alloweddomain_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alloweddomain",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
