# Generated by Django 5.0.3 on 2024-07-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Linkfeed", "0004_comment_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importedrssfeed",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="imported_rss_feed",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usercss",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_imported_rss_feed_post",
        ),
        migrations.RemoveField(
            model_name="post",
            name="repost_count",
        ),
        migrations.AddField(
            model_name="profile",
            name="domain",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AllowedDomain",
        ),
        migrations.DeleteModel(
            name="ImportedRSSFeed",
        ),
        migrations.DeleteModel(
            name="PostLike",
        ),
        migrations.DeleteModel(
            name="UserCSS",
        ),
    ]
